### ISSUE TITLE
Recurrent Highway Networks - some remarks

### ISSUE THREAD

**Issue by julian121266** [LeavesBreathe/tensorflow_with_latest_papers#1]
Hi LeavesBreathe,

Thank you for making these tensorflow implementations of new papers public. I really appreciate it. 

There are just two remarks I would like to make. 
First, the original setup of Recurrent Highway Networks uses the input only in the first of the stacked highway layers. If I am not mistaken, the current implementation uses the input in all stacked highway layers. This is, of course, in the end a design choice.

Second, it is probably best to test Recurrent Highway Networks on large language modeling datasets. From the experiments we ran, it seemed that the network overfits very easily on the PTB dataset. A smart regularization scheme will be necessary otherwise only qualitative results (as reported on PTB in the paper) will be achieved. Hence training on large datasets is more suitable to do the network justice. Even then the network overfit without regularization on the Hutter Wikipedia dataset.

Thanks again for the good work.

Best wishes,
Julian

**Comment by LeavesBreathe** [comment]
Hey @julian121266,

Thanks for addressing these two issues. Firstly, I reviewed the paper, and it does seem that they opt to just use the inputs on the first layer, I have added an option on the mulint version of the recurrent highway to turn on and off using the input on subsequent layers. This also applies to the gating function as well. 

Harder datasets are probably more preferable. I think at this point though, users can simply supply their own dataset that they want to use? I feel that having a larger dataset will make the repo itself very large. I'm going to close this issue as I think both points are addressed but feel free to reopen it or start a new issue.
