### ISSUE TITLE
Hierarchical Multiscale Recurrent Neural Networks, arxiv 1609.01704v2

### ISSUE THREAD

**Issue by rgobbel** [LeavesBreathe/tensorflow_with_latest_papers#6]
http://arxiv.org/abs/1609.01704v2

**Comment by rgobbel** [comment]
Looks like it's in there--thanks. One of the authors says a revised version, with code, will be out any day now.

**Comment by talpay** [comment]
Any update?

**Comment by maziarmf** [comment]
Any news??

**Comment by maziarmf** [comment]
It seems it has been implemented 2 months ago. Here is the link:

https://github.com/n-s-f/hierarchical-rnn/tree/master/hmlstm
